version: "3"
services:
  client:
    image: "sayandafadar/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "sayandafadar/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "sayandafadar/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "sayandafadar/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

# {
#     "AWSEBDockerrunVersion": 2,
#     "containerDefinitions": [
#         {
#             "name": "client",
#             "image": "sayandafadar/multi-client",
#             "hostname": "client",
#             "essential": false
#         },
#         {
#             "name": "server",
#             "image": "sayandafadar/multi-server",
#             "hostname": "api",
#             "essential": false
#         },
#         {
#             "name": "worker",
#             "image": "sayandafadar/multi-worker",
#             "hostname": "worker",
#             "essential": false
#         },
#         {
#             "name": "nginx",
#             "image": "sayandafadar/multi-nginx",
#             "hostname": "nginx",
#             "essential": true,
#             "portMappings": [
#                 {
#                     "hostPort": 80,
#                     "containerPort": 80
#                 }
#             ],
#             "links": [
#                 "server",
#                 "client"
#             ]
#         }
#     ]
# }
