name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t sayandafadar/multi-client ./client
      - run: docker build -t sayandafadar/multi-nginx ./nginx
      - run: docker build -t sayandafadar/multi-server ./server
      - run: docker build -t sayandafadar/multi-worker ./worker

      - run: docker push sayandafadar/multi-client
      - run: docker push sayandafadar/multi-nginx
      - run: docker push sayandafadar/multi-server
      - run: docker push sayandafadar/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker-container
          environment_name: Multi-docker-container-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-954976286224
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
