name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t sayandafadar/multi-client ./client
      - run: docker build -t sayandafadar/multi-nginx ./nginx
      - run: docker build -t sayandafadar/multi-server ./server
      - run: docker build -t sayandafadar/multi-worker ./worker

      - run: docker push sayandafadar/multi-client
      - run: docker push sayandafadar/multi-nginx
      - run: docker push sayandafadar/multi-server
      - run: docker push sayandafadar/multi-worker
